-- Usernames and privacy (ADR 0026). Generated by drizzle-kit, then hand-finished: the
-- username column arrives nullable, is backfilled for every existing account, and only then
-- becomes NOT NULL; the generator, the auth trigger, the directory view and the two lookups
-- are SQL that the schema cannot express. Mirrors `src/domain/username.ts`.

-- 1. The reserved list, written once in SQL. The check constraint and the generator both call
--    it, and a test holds it to the TypeScript copy word for word.
CREATE OR REPLACE FUNCTION public.username_reserved(candidate text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE
AS $$
DECLARE
  RESERVED_USERNAMES text[] := array['me', 'u', 'profile', 'settings', 'friends', 'compare', 'leaderboard', 'admin', 'overload', 'coach', 'api', 'auth', 'login', 'signup', 'welcome', 'today', 'runs', 'history', 'progress', 'gyms', 'exercises', 'workouts', 'preview', 'support', 'help'];
BEGIN
  RETURN candidate = ANY (RESERVED_USERNAMES);
END;
$$;
--> statement-breakpoint

-- 2. Whether a canonical (trimmed, lowercased) name meets every rule: 3–20 characters of
--    lowercase letters, digits, dots and underscores, a letter or digit at each end, no doubled
--    dot, not reserved. Says nothing about whether it is taken.
CREATE OR REPLACE FUNCTION public.username_valid(candidate text) RETURNS boolean
LANGUAGE sql IMMUTABLE
AS $$
  SELECT candidate IS NOT NULL
    AND candidate ~ '^[a-z0-9][a-z0-9._]{1,18}[a-z0-9]$'
    AND candidate NOT LIKE '%..%'
    AND NOT public.username_reserved(candidate);
$$;
--> statement-breakpoint

-- 3. A free username. `preferred` wins when it is valid and unused; otherwise `base` (the local
--    part of an email) is sanitised exactly as `usernameFromEmail` does it and suffixed 2, 3, …
--    until free; and when the base yields nothing, "athlete_" and eight hex characters of a
--    fresh id. SECURITY DEFINER because it must see every username to know which are taken,
--    and VOLATILE so a backfill loop sees the names it has just handed out.
CREATE OR REPLACE FUNCTION public.generate_username(base text, preferred text) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  candidate text;
  stem text;
  n integer := 2;
BEGIN
  candidate := lower(trim(coalesce(preferred, '')));
  IF public.username_valid(candidate)
     AND NOT EXISTS (SELECT 1 FROM public.profiles WHERE username = candidate) THEN
    RETURN candidate;
  END IF;

  stem := lower(coalesce(base, ''));
  stem := regexp_replace(stem, '[^a-z0-9._]', '', 'g');
  stem := regexp_replace(stem, '\.{2,}', '.', 'g');
  stem := regexp_replace(stem, '^[._]+|[._]+$', '', 'g');
  stem := regexp_replace(left(stem, 20), '[._]+$', '');
  IF stem = '' THEN
    stem := 'athlete_' || left(replace(gen_random_uuid()::text, '-', ''), 8);
  ELSIF length(stem) < 3 THEN
    stem := rpad(stem, 3, '0');
  END IF;

  candidate := stem;
  WHILE NOT public.username_valid(candidate)
     OR EXISTS (SELECT 1 FROM public.profiles WHERE username = candidate) LOOP
    -- Room for the suffix, and never a dot left before it.
    candidate := regexp_replace(left(stem, 20 - length(n::text)), '[._]+$', '') || n::text;
    n := n + 1;
  END LOOP;
  RETURN candidate;
END;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.generate_username(text, text) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION public.generate_username(text, text) TO authenticated, service_role;
--> statement-breakpoint

-- 4. The columns. Username is nullable for the length of the backfill below.
ALTER TABLE "profiles" ADD COLUMN "username" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "follow_approval" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "share_training" boolean DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "share_body_weight" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "discoverable_by_email" boolean DEFAULT true NOT NULL;--> statement-breakpoint

-- 5. Every existing account gets a username from its email, oldest account first, so the
--    person who has been here longest keeps the plain name and later namesakes take the suffix.
DO $$
DECLARE
  account record;
BEGIN
  FOR account IN
    SELECT id, email FROM public.profiles WHERE username IS NULL ORDER BY created_at, id
  LOOP
    UPDATE public.profiles
      SET username = public.generate_username(split_part(coalesce(account.email, ''), '@', 1), NULL)
      WHERE id = account.id;
  END LOOP;
END $$;
--> statement-breakpoint
ALTER TABLE "profiles" ALTER COLUMN "username" SET NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_username_uq" ON "profiles" USING btree ("username");--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_username_chk" CHECK (username ~ '^[a-z0-9][a-z0-9._]{1,18}[a-z0-9]$'
        and username not like '%..%' and not public.username_reserved(username));--> statement-breakpoint

-- 6. New accounts: the auth trigger (from 0001) now sets the username too, from what the
--    signup form asked for when that is still free, otherwise from the email. A race on the
--    unique index between two signups picking the same name is retried with a fresh one, so
--    sign-up itself never fails on a username.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  preferred text := NEW.raw_user_meta_data->>'username';
  attempt integer := 0;
BEGIN
  LOOP
    BEGIN
      INSERT INTO public.profiles (id, email, display_name, username)
      VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'display_name', split_part(COALESCE(NEW.email, ''), '@', 1)),
        public.generate_username(split_part(COALESCE(NEW.email, ''), '@', 1), preferred)
      )
      ON CONFLICT (id) DO NOTHING;
      RETURN NEW;
    EXCEPTION WHEN unique_violation THEN
      attempt := attempt + 1;
      preferred := NULL;
      IF attempt >= 3 THEN RAISE; END IF;
    END;
  END LOOP;
END;
$$;
--> statement-breakpoint

-- 7. The directory: the only facts about an account that any other account may read. Owned by
--    the migration role, so it reads profiles without RLS; the grant is what lets the app's
--    `authenticated` role select from it.
CREATE VIEW "public"."profile_directory" WITH (security_barrier = true) AS (select id, username, display_name, created_at as joined_at, follow_approval from public.profiles);--> statement-breakpoint
GRANT SELECT ON public.profile_directory TO authenticated, service_role;
--> statement-breakpoint

-- 8. Two lookups that must not enumerate. An exact email match, only for accounts that allow
--    it, returning directory rows and never the address; and whether a name is free, which
--    the signup form asks before an account exists, so anon may call it.
CREATE OR REPLACE FUNCTION public.find_profile_by_email(candidate text)
RETURNS SETOF public.profile_directory
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT d.*
  FROM public.profile_directory d
  JOIN public.profiles p ON p.id = d.id
  WHERE p.discoverable_by_email
    AND lower(p.email) = lower(trim(candidate))
  LIMIT 1;
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.find_profile_by_email(text) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION public.find_profile_by_email(text) TO authenticated, service_role;
--> statement-breakpoint
CREATE OR REPLACE FUNCTION public.username_available(candidate text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT public.username_valid(lower(trim(candidate)))
    AND NOT EXISTS (SELECT 1 FROM public.profiles WHERE username = lower(trim(candidate)));
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.username_available(text) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION public.username_available(text) TO anon, authenticated, service_role;
