-- Following (ADR 0026). Generated by drizzle-kit, then hand-finished: the two triggers that
-- decide a follow's status, the visibility helper the shared tables will use, and the
-- directory view replaced in place rather than dropped, since find_profile_by_email() returns
-- its row type. The counts it gains are of accepted follows only.

CREATE TYPE "public"."follow_status" AS ENUM('pending', 'accepted');--> statement-breakpoint
CREATE TABLE "follows" (
	"follower_id" uuid NOT NULL,
	"followee_id" uuid NOT NULL,
	"status" "follow_status" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"accepted_at" timestamp with time zone,
	CONSTRAINT "follows_follower_id_followee_id_pk" PRIMARY KEY("follower_id","followee_id"),
	CONSTRAINT "follows_not_self_chk" CHECK (follower_id <> followee_id)
);
--> statement-breakpoint
ALTER TABLE "follows" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_id_profiles_id_fk" FOREIGN KEY ("follower_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follows" ADD CONSTRAINT "follows_followee_id_profiles_id_fk" FOREIGN KEY ("followee_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "follows_followee_status_idx" ON "follows" USING btree ("followee_id","status");--> statement-breakpoint
CREATE INDEX "follows_follower_status_idx" ON "follows" USING btree ("follower_id","status");--> statement-breakpoint
CREATE OR REPLACE VIEW "public"."profile_directory" WITH (security_barrier = true) AS (select p.id, p.username, p.display_name, p.created_at as joined_at, p.follow_approval,
      (select count(*)::integer from public.follows f where f.followee_id = p.id and f.status = 'accepted') as followers,
      (select count(*)::integer from public.follows f where f.follower_id = p.id and f.status = 'accepted') as following
      from public.profiles p);--> statement-breakpoint
CREATE POLICY "follows_select" ON "follows" AS PERMISSIVE FOR SELECT TO "authenticated" USING (follower_id = (select auth.uid()) or followee_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "follows_insert" ON "follows" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (follower_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "follows_update" ON "follows" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (followee_id = (select auth.uid())) WITH CHECK (followee_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "follows_delete" ON "follows" AS PERMISSIVE FOR DELETE TO "authenticated" USING (follower_id = (select auth.uid()) or followee_id = (select auth.uid()));--> statement-breakpoint

-- 1. Nothing the client says about status is trusted. On insert the followee's own setting
--    decides: approval on means the row starts pending, off means it is accepted at once.
--    SECURITY DEFINER because the follower may not read the followee's profile row.
CREATE OR REPLACE FUNCTION public.follows_set_status() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  needs_approval boolean;
BEGIN
  SELECT follow_approval INTO needs_approval FROM public.profiles WHERE id = NEW.followee_id;
  IF needs_approval IS NULL THEN
    RAISE EXCEPTION 'no such profile: %', NEW.followee_id USING ERRCODE = 'foreign_key_violation';
  END IF;
  IF needs_approval THEN
    NEW.status := 'pending';
    NEW.accepted_at := NULL;
  ELSE
    NEW.status := 'accepted';
    NEW.accepted_at := now();
  END IF;
  NEW.created_at := now();
  RETURN NEW;
END;
$$;
--> statement-breakpoint
DROP TRIGGER IF EXISTS follows_set_status ON public.follows;
--> statement-breakpoint
CREATE TRIGGER follows_set_status
  BEFORE INSERT ON public.follows
  FOR EACH ROW EXECUTE FUNCTION public.follows_set_status();
--> statement-breakpoint

-- 2. The only update a follow admits is being accepted, and the row keeps its own dates.
CREATE OR REPLACE FUNCTION public.follows_accept_only() RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.follower_id <> OLD.follower_id OR NEW.followee_id <> OLD.followee_id THEN
    RAISE EXCEPTION 'a follow cannot be moved' USING ERRCODE = 'check_violation';
  END IF;
  IF OLD.status = 'pending' AND NEW.status = 'accepted' THEN
    NEW.accepted_at := now();
  ELSIF NEW.status <> OLD.status THEN
    RAISE EXCEPTION 'a follow can only be accepted' USING ERRCODE = 'check_violation';
  ELSE
    NEW.accepted_at := OLD.accepted_at;
  END IF;
  NEW.created_at := OLD.created_at;
  RETURN NEW;
END;
$$;
--> statement-breakpoint
DROP TRIGGER IF EXISTS follows_accept_only ON public.follows;
--> statement-breakpoint
CREATE TRIGGER follows_accept_only
  BEFORE UPDATE ON public.follows
  FOR EACH ROW EXECUTE FUNCTION public.follows_accept_only();
--> statement-breakpoint

-- 3. Whether the caller may see an account's shared training: their own, or an accepted
--    follow of an account that shares. A function rather than an inline policy subquery,
--    because a subquery on profiles inside a policy would itself be filtered by the profile
--    owner policy and return nothing for anyone but you.
CREATE OR REPLACE FUNCTION public.can_view_training(owner uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT owner = auth.uid()
    OR (
      EXISTS (
        SELECT 1 FROM public.follows
        WHERE follower_id = auth.uid() AND followee_id = owner AND status = 'accepted'
      )
      AND (SELECT share_training FROM public.profiles WHERE id = owner)
    );
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.can_view_training(uuid) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION public.can_view_training(uuid) TO authenticated, service_role;
