-- Shared stats (ADR 0026, plan §5.3). Generated by drizzle-kit, then hand-finished: the
-- visibility helper for body weight is written first, because the policy on
-- shared_body_weight names it. `can_view_training()` already exists from migration 0020.

-- Whether the caller may see an account's body weight: their own, or an account whose
-- training they may see, when both of them have opted in. SECURITY DEFINER for the same
-- reason as can_view_training(): a policy subquery on profiles would see only the caller's row.
CREATE OR REPLACE FUNCTION public.can_view_body_weight(owner uuid) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT owner = auth.uid()
    OR (
      public.can_view_training(owner)
      AND coalesce((SELECT share_body_weight FROM public.profiles WHERE id = owner), false)
      AND coalesce((SELECT share_body_weight FROM public.profiles WHERE id = auth.uid()), false)
    );
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.can_view_body_weight(uuid) FROM PUBLIC;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION public.can_view_body_weight(uuid) TO authenticated, service_role;
--> statement-breakpoint
CREATE TYPE "public"."training_sport" AS ENUM('workout', 'run');--> statement-breakpoint
CREATE TABLE "shared_body_weight" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"weight_kg" numeric(5, 2) NOT NULL,
	"measured_on" date NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "shared_body_weight" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "shared_exercise_stats" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"workout_session_id" uuid NOT NULL,
	"exercise_id" uuid NOT NULL,
	"occurred_on" date NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"comparable" boolean NOT NULL,
	"working_sets" integer NOT NULL,
	"total_reps" integer,
	"top_weight_kg" numeric(7, 2),
	"best_e1rm_kg" numeric(7, 2),
	"best_set_volume_kg" numeric(9, 2),
	"most_reps" integer,
	"longest_duration_seconds" integer,
	"longest_distance_meters" numeric(8, 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "shared_exercise_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "shared_session_stats" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"sport" "training_sport" NOT NULL,
	"source_id" uuid NOT NULL,
	"title" text NOT NULL,
	"occurred_on" date NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"duration_seconds" integer NOT NULL,
	"working_sets" integer DEFAULT 0 NOT NULL,
	"volume_kg" numeric(10, 2) DEFAULT 0 NOT NULL,
	"distance_meters" numeric(9, 1),
	"pace_seconds_per_km" numeric(7, 1),
	"muscle_sets" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"records" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "shared_session_stats" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "shared_body_weight" ADD CONSTRAINT "shared_body_weight_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shared_exercise_stats" ADD CONSTRAINT "shared_exercise_stats_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shared_exercise_stats" ADD CONSTRAINT "shared_exercise_stats_exercise_id_exercises_id_fk" FOREIGN KEY ("exercise_id") REFERENCES "public"."exercises"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shared_session_stats" ADD CONSTRAINT "shared_session_stats_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "shared_exercise_stats_session_exercise_uq" ON "shared_exercise_stats" USING btree ("user_id","workout_session_id","exercise_id");--> statement-breakpoint
CREATE INDEX "shared_exercise_stats_user_exercise_day_idx" ON "shared_exercise_stats" USING btree ("user_id","exercise_id","occurred_on" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "shared_exercise_stats_comparable_idx" ON "shared_exercise_stats" USING btree ("exercise_id","comparable") WHERE comparable;--> statement-breakpoint
CREATE UNIQUE INDEX "shared_session_stats_source_uq" ON "shared_session_stats" USING btree ("user_id","sport","source_id");--> statement-breakpoint
CREATE INDEX "shared_session_stats_user_sport_day_idx" ON "shared_session_stats" USING btree ("user_id","sport","occurred_on" DESC NULLS LAST);--> statement-breakpoint
CREATE POLICY "shared_body_weight_select" ON "shared_body_weight" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.can_view_body_weight(user_id));--> statement-breakpoint
CREATE POLICY "shared_body_weight_insert" ON "shared_body_weight" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_body_weight_update" ON "shared_body_weight" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_body_weight_delete" ON "shared_body_weight" AS PERMISSIVE FOR DELETE TO "authenticated" USING (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_exercise_stats_select" ON "shared_exercise_stats" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.can_view_training(user_id));--> statement-breakpoint
CREATE POLICY "shared_exercise_stats_insert" ON "shared_exercise_stats" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_exercise_stats_update" ON "shared_exercise_stats" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_exercise_stats_delete" ON "shared_exercise_stats" AS PERMISSIVE FOR DELETE TO "authenticated" USING (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_session_stats_select" ON "shared_session_stats" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.can_view_training(user_id));--> statement-breakpoint
CREATE POLICY "shared_session_stats_insert" ON "shared_session_stats" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_session_stats_update" ON "shared_session_stats" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (user_id = (select auth.uid())) WITH CHECK (user_id = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "shared_session_stats_delete" ON "shared_session_stats" AS PERMISSIVE FOR DELETE TO "authenticated" USING (user_id = (select auth.uid()));
