import { createHash } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

/** Where the drawings' vector sources live, one file per equipment type or combination slug. */
export const DRAWINGS_FOLDER = "src/components/equipment-art/svg";
export const DRAWINGS_MODULE = "src/components/equipment-art/drawings.generated.ts";

/** Every drawing's markup, by slug, in slug order, with line breaks and indentation removed. */
export async function readDrawings(): Promise<Record<string, string>> {
  const files = (await readdir(DRAWINGS_FOLDER)).filter((file) => file.endsWith(".svg")).sort();
  const drawings: Record<string, string> = {};
  for (const file of files) {
    const markup = await readFile(path.join(DRAWINGS_FOLDER, file), "utf8");
    drawings[file.replace(/\.svg$/, "")] = markup
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean)
      .join("");
  }
  return drawings;
}

/** A short fingerprint of a drawing, so its address changes whenever it is redrawn. */
export function drawingVersion(markup: string): string {
  return createHash("sha256").update(markup).digest("hex").slice(0, 10);
}

/** The generated module: each drawing and its fingerprint. */
export async function renderDrawingsModule(): Promise<string> {
  const drawings = await readDrawings();
  const entries = Object.entries(drawings)
    .map(
      ([slug, markup]) =>
        `  ${JSON.stringify(slug)}: {\n    version: ${JSON.stringify(drawingVersion(markup))},\n    svg: ${JSON.stringify(markup)},\n  },`,
    )
    .join("\n");
  return `// Generated by scripts/equipment-art.ts from ${DRAWINGS_FOLDER}. Do not edit by hand.\n\n/** Each equipment drawing, by slug: its markup and a fingerprint for its address. */\nexport const EQUIPMENT_DRAWINGS: Readonly<Record<string, { version: string; svg: string }>> = {\n${entries}\n};\n`;
}
